# Site settings
title: Fun with Machine Learning and Computer Vision
email: peter.leslie.cho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Various ideas, problems and projects in machine learning with applications
  to computer vision that I find interesting.  Hopefully you may too...
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petercho.github.io" # the base hostname & protocol for your site
url_local: "http://127.0.0.1:4000" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  PeterCho

# Build settings
markdown: kramdown
